apiVersion: apps/v1
kind: Deployment
metadata:
  name: manjunathachar-deploy
  labels:
    app: healthcare_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare_app
  template:
    metadata:
      labels:
        app: healthcare_app
    spec:
      containers:
      - name: health-care-container
        image: manjunathachar/healthcare_app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: manjunathachar-np-service
  labels:
    app: healthcare_app
spec:
  selector:
    app: healthcare_app
  type: NodePort
  ports:
  - nodePort: 30410
    port: 9090
    targetPort: 9090


