apiVersion: apps/v1
kind: Deployment
metadata:
  name: manjunathachar-deploy
  labels:
    app:  healthcare_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare_app
  template:
    metadata:
      labels:
        app: healthcare_app
    spec:
      containers:
      - name: health-care-container
        image: manjunathachar/healthcare_app:v1.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loksai-np-service
  labels:
    app: healthcare_app
spec:
  selector:
    app: healthcare_app

  type: NodePort
  ports:
  - nodePort: 31000
    port: 8080
    targetPort: 8080
